services:
  mongo:
    image: mongo:7
    container_name: skillbridge-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: skillbridge
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

